### PR TITLE
Minor cleanup for all scripts

### PR DESCRIPTION
**Pull request by valkyrienyanko**
This PR does the following
- Adds a [file-scoped](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces) [namespace](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace) to every script
- Adds [global usings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#global-modifier) to Globals.cs and removes all implicit duplicate usings across all scripts
- Updates net6.0 to net7.0
- Slightly improves readability across all scripts

P.S. [2 scripts](https://github.com/Nekompiliuoja/Champions-of-the-Realm/commit/b7c2459ac413992a6aa15002502ae6e032f76c05) have had all their fields converted to properties in PascalFormat. Read [this](https://stackoverflow.com/questions/2374416/why-use-simple-properties-instead-of-fields-in-c) on why you should use properties over fields. If you like it, I'll do it for the rest of all the scripts. Not to mention I'm using VS2022 IDE and codelens only works on properties so I can't see the "x references" above each field.

### CODE REVIEW

**Review by Karolinskis — CHANGES_REQUESTED** [review]
Using fields is usually practiced in private classes that are not intended to share data with other classes, in your commit you changed tween, swingDuration, reloadDuration to properties. tween is not accessed in any other class, so it should stay as a field, while swingDuration and reloadDuration was an oversight by us and should use properties.

Other than that great work! 😄

**Comment by Karolinskis** [comment]
Not being able to see references on fields is a known [issue](https://github.com/dotnet/roslyn/issues/23908). Personally I'd suggest moving to Visual Studio Code, because here you can see references above fields.

**Comment by valkyrienyanko** [comment]
I reverted everything back to fields except for `SwingDuration` and `ReloadDuration`. I wish VS2022 would show the references for not just props but for fields as well. Oh well I might just move over to VSCode because of this.

**Review by Elijuszek — CHANGES_REQUESTED** [review]
Unresolved conflicts. Everything else looks alright.

**Comment by valkyrienyanko** [comment]
Conflict resolved.

**Review by Karolinskis — APPROVED** [review]

**Pull request merged**
